### ISSUE TITLE
Error: this zip is not a magisk module

### ISSUE THREAD

**Issue by eallion** [WordlessEcho/Noto-Super-OTC-Installer#3]
Got an error on magisk installing

- Device: crDroid 7.2 (Android 11)
- Magisk: latest 21.4
- Magisk Manager: latest 8.0.7
- Noto-Super-OTC-Installer: latest 1.5 

![photo_2021-01-25_20-10-30](https://user-images.githubusercontent.com/1698841/105704256-7da2ba80-5f49-11eb-91b3-006fd4440f94.jpg)

**Comment by jks15satoshi** [comment]
I guess you downloaded the source code zip file from the release page. That is not a Magisk module file indeed.
BTW, I just found that there is not actual Magisk module zip file from the latest release.

**Comment by jks15satoshi** [comment]
Extract your downloaded zip file, and re-zip with the inner four items from the extracted folder. Read [this](https://topjohnwu.github.io/Magisk/guides.html#magisk-module-installer) as references.

**Comment by eallion** [comment]
It works thx
